# generated by datamodel-codegen:
#   filename:  artist.json
#   timestamp: 2023-08-09T03:14:10+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Result(BaseModel):
    field_type: str = Field(..., alias='_type')
    annotation_count: Optional[str] = None
    api_path: str
    artist_names: Optional[str] = None
    full_title: Optional[str] = None
    header_image_thumbnail_url: Optional[str] = None
    header_image_url: str
    id: int
    instrumental: None
    lyrics_owner_id: None
    lyrics_state: None
    lyrics_updated_at: None
    path: Optional[str] = None
    pyongs_count: Optional[int] = None
    relationships_index_url: None
    release_date_components: None
    release_date_for_display: None
    release_date_with_abbreviated_month_for_display: None
    song_art_image_thumbnail_url: None
    song_art_image_url: None
    stats: None
    title: None
    title_with_featured: None
    updated_by_human_at: None
    url: str
    featured_artists: None
    primary_artist: None
    image_url: str
    index_character: str
    is_meme_verified: bool
    is_verified: bool
    name: str
    slug: str
    cover_art_thumbnail_url: None
    cover_art_url: None
    name_with_artist: None
    artist: None
    article_url: None
    author_list_for_display: None
    dek: None
    description: None
    dfp_kv: None
    duration: None
    poster_attributes: None
    poster_url: None
    provider: None
    provider_id: None
    provider_params: None
    short_title: None
    type: None
    video_attributes: None
    current_user_metadata: None
    published_at: None
    view_count: None
    author: None
    sponsorship: None
    article_type: None
    draft: None
    featured_slot: None
    for_homepage: None
    for_mobile: None
    generic_sponsorship: None
    preview_image: None
    sponsor_image: None
    sponsor_image_style: None
    sponsor_link: None
    sponsor_phrase: None
    sponsored: None
    votes_total: None
    about_me_summary: None
    avatar: None
    human_readable_role_for_display: None
    iq: None
    login: None
    role_for_display: None


class Hit(BaseModel):
    highlights: List
    index: str
    type: str
    result: Result


class Section(BaseModel):
    type: str
    hits: List[Hit]


class Model(BaseModel):
    sections: List[Section]
